<?php
/*
 * @file
 * Clientside validation install file
 */

/**
 * Implements hook_enable().
 */
function clientside_validation_enable() {
  //support for module like e.g. select_or_other
  db_update('system')
    ->fields(array(
      'weight' => 5,
    ))
    ->condition('type', 'module')
    ->condition('name', 'clientside_validation')
    ->execute();
}

/**
 * Implements hook_schema()
 */
function clientside_validation_schema() {
  $schema = array();
  $schema['clientside_validation_settings'] = array(
    'description' => 'Table for storing Clientside Validation Settings',
    'fields' => array(
      'cvsid' => array(
        'description' => 'The primary identifier for the clientside validation settings',
        'type' => 'serial',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'type' => array(
        'description' => 'The type of setting: content_type, webform or custom',
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => '',
      ),
      'status' => array(
        'description' => 'The status for this form. 1 for enabled (validate), 0 for disabled (don\'t validate)',
        'type' => 'int',
        'not null' => TRUE,
        'default' => 0,
        'size' => 'tiny',
      ),
      'form_id' => array(
        'description' => 'The form id these settings apply to',
        'type' => 'varchar',
        'length' => 255,
        'not null' => TRUE,
        'default' => '',
      ),
      'settings' => array(
        'type' => 'blob',
        'not null' => TRUE,
        'size' => 'big',
        'translatable' => TRUE,
      ),
    ),
    'indexes' => array(
      'clientside_validation_settings_form_id' => array('form_id'),
      'clientside_validation_settings_type' => array('type'),
      'clientside_validation_settings_form_id_type' => array('form_id', 'type'),
    ),
    'unique keys' => array(
      'cvs_form_id' => array('form_id'),
    ),
    'primary key' => array('cvsid'),
  );
  return $schema;
}

/**
 * Clientside validation was split up into form validation, webform validation and fapi validation.
 * This update enables the form and webform clientside validation module. It does not enable the
 * fapi clientside validation module, because it's a new feature since this release.
 */
function clientside_validation_update_7100() {
  module_enable(array('clientside_validation_form', 'clientside_validation_webform'));
}

/**
 * The settings for Clientside Validation were restructured and put into a separate table,
 * This update will create this table.
 */
function clientside_validation_update_7101() {
  if(!db_table_exists('clientside_validation_settings')) {
    db_create_table('clientside_validation_settings', drupal_get_schema('clientside_validation_settings', TRUE));
  }
}
