<?php

/**
 * @file
 * Install functions for Clientside Validation Testswarm.
 */

/**
 * Import the webform needed to test Clientside Validation Webform.
 */
function clientside_validation_testswarm_update_7101() {
  $nodenames = variable_get('clientside_validation_testswarm_nodenames', array());
  if (empty($nodenames)) {
    clientside_validation_testswarm_enable();
  }
}

/**
 * Add the path alias and menu link for the default node.
 */
function clientside_validation_testswarm_update_7102() {
  if (module_exists('path')) {
    foreach (variable_get('clientside_validation_testswarm_nodenames', array()) as $machine_name => $nid) {
      $node = node_load($nid);
      $path = array(
        'source' => 'node/' . $nid,
        'alias' => 'clientsidevalidation/tests/' . $machine_name,
      );
      if (isset($node->language)) {
        $path['language'] = $node->language;
      }
      path_save($path);
    }
  }
  $link = array(
    'menu_name' => 'navigation',
    'link_path' => 'node-name/webform',
    'router_path' => 'node/%',
    'link_title' => 'Clientside Validation Webform Tests',
    'options' => array(
      'attributes' => array(
        'title' => 'Test Clientside Validation on form elements provided by the Webform module',
      ),
    ),
    'module' => 'menu',
    'hidden' => '0',
    'external' => '0',
    'has_children' => '0',
    'expanded' => '0',
    'weight' => '0',
    'parent_path' => 'clientsidevalidation/tests',
    'identifier' => 'navigation:node-name/webform',
  );
  defaultcontent_import_menu_link($link['identifier'], $link);
}