<?php
/**
 * Implements hook_requirements().
 */
function clientside_validation_field_validation_requirements() {
  $t = get_t();
  $info = system_get_info('module', 'field_validation');
  $requirements['field_validation'] = array(
    'title' => $t('Field validation'),
    'value' => $info['version'],
  );
  $version = explode('-', $info['version']);
  $version = explode('.', $version[1]);
  //check for version (format = 7.x-1.0)
  if (((int)$version[0] >= 2)) {
    $requirements['field_validation']['description'] = $t('The Field Validation
      module\'s version needs to be in the 1.x range.');
    $requirements['field_validation']['severity'] = REQUIREMENT_ERROR;
  }
  return $requirements;
}
